# Site settings
title: Eric Squires
email: contact@eric-squires.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts, ruminations and rants on software engineering and
  similarly interesting topics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.eric-squires.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  EricSquires

# Build settings
markdown: kramdown
